version: '3.8'

services:
  dbt:
    build: .
    container_name: dbt-core
    volumes:
      - .:/usr/app
      - ./.dbt:/root/.dbt
      - ../secrets/gcp-key.json:/usr/app/gcp-key.json
    ports:
      - "7999:7999"
    stdin_open: true
    tty: true

